package:
  name: wavepy
  version: '0.1.1'

source:
  git_url: https://github.com/wavepy/wavepy.git
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools
 
  run:
    - python
    - numpy    
    
test:
  # Python imports
  imports:
    - wavepy
    - wavepy.module_01
    - wavepy.module_02

about:
  home: http://wavepy.readthedocs.org
  license: BSD-3
  summary: 'X-ray intereferometry'
